create OR REPLACE PROCEDURE incluir_cliente
(p_ID IN CLIENTE.ID%TYPE, p_RAZAO_SOCIAL IN cliente.razao_social%TYPE,
p_CNPJ IN cliente.cnpj%TYPE, p_SEGMERCADO_ID IN cliente.segmercado_id%TYPE,
p_FATURAMENTO_PREVISTO IN cliente.faturamento_previsto%TYPE)

IS
    v_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN

    v_CATEGORIA := categoria_cliente(p_FATURAMENTO_PREVISTO);
    INSERT INTO CLIENTE (ID, RAZAO_SOCIAL, CNPJ, SEGMERCADO_ID, DATA_INCLUSAO, FATURAMENTO_PREVISTO, CATEGORIA)
    VALUES(p_ID, p_RAZAO_SOCIAL, p_CNPJ, p_SEGMERCADO_ID, SYSDATE, p_FATURAMENTO_PREVISTO, v_CATEGORIA);
    COMMIT;
END;

SELECT * FROM CLIENTE;
DELETE FROM CLIENTE;

EXECUTE incluir_cliente(2, 'SUPERMERCADO IJK', '0881240900114', 1, 90000);